import type { AppState } from '../types'

export const SAMPLE_DATA: Pick<AppState, 'projects' | 'formulations' | 'samples' | 'feedback' | 'gateReviews' | 'materials'> = {
  projects: [
    {
      id: 'proj-1',
      projectCode: 'PRJ-2025-001',
      name: '2X Pain Relief',
      category: 'Kratom Shot',
      description: '80mg MIT shot using 10:1 filtered kratom extract. All-natural formula with classic herbal profile. 1.9oz bottle.',
      targetProfile: 'Very thick, dark brown. Strong astringent herbal smell. pH 2.5–3.2.',
      status: 'active',
      stage: 'G4',
      priority: 'high',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '1.9oz (56mL) shot. 80mg MIT (78–84mg range). All-natural preservatives. Shelf stable 2 years.',
      targetActives: 'Mitragynine 80mg (target), 7-OH-Mitragynine <0.04%',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-03-11T12:00:00Z',
    },
    {
      id: 'proj-2',
      projectCode: 'PRJ-2025-002',
      name: 'Energy & Focus',
      category: 'Kratom Shot',
      description: '40mg MIT energy shot built on a 10:1 extract base with ginseng, vitamin C, and tea flavor. 1.9oz bottle.',
      targetProfile: 'Thick with undissolved solids. Brown. Strong aseptic herbal. pH 2.5–3.2.',
      status: 'active',
      stage: 'G4',
      priority: 'high',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '1.9oz (56mL) shot. 40mg MIT (38–44mg range). All-natural formula. Shelf stable.',
      targetActives: 'Mitragynine 40mg, 7-OH-Mitragynine <0.04%',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-03-11T12:00:00Z',
    },
    {
      id: 'proj-3',
      projectCode: 'PRJ-2025-003',
      name: 'Relax & Unwind',
      category: 'Kava Shot',
      description: 'Kava-only relaxation shot. 520mg kavalactones + 300mg GABA with raspberry-lemon flavor. No kratom. 1.9oz bottle.',
      targetProfile: 'Yellow, translucent. Medium yellow color. Herbal kava aroma. pH 3.5–4.0.',
      status: 'active',
      stage: 'G4',
      priority: 'high',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '1.9oz (56mL) shot. 520mg kavalactones (515–525mg range). 300mg GABA. Natural formula. Shelf stable.',
      targetActives: 'Kavalactones 520mg, GABA 300mg',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-03-12T12:00:00Z',
    },
    {
      id: 'proj-4',
      projectCode: 'PRJ-2025-004',
      name: 'Natural Energy',
      category: 'Kratom Shot',
      description: '20mg MIT low-dose energy shot with cordyceps, L-carnitine, B12, and tropical flavor. Clean, translucent format. 1.9oz bottle.',
      targetProfile: 'Translucent, no solids. Tan to dirty brown. Tropical fruity. pH 3.5–4.0.',
      status: 'active',
      stage: 'G4',
      priority: 'critical',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '1.9oz (56mL) shot. 20mg MIT (18–24mg range). Cordyceps + L-Carnitine functional stack. All-natural. Shelf stable 2 years.',
      targetActives: 'Mitragynine 20mg, Cordyceps 40% Extract, L-Carnitine, Vitamin B12',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-12-05T12:00:00Z',
    },
    {
      id: 'proj-5',
      projectCode: 'PRJ-2025-005',
      name: 'Stress Relief',
      category: 'Kratom + Kava Shot',
      description: 'Dual-active shot combining 40mg MIT with 520mg kavalactones. Adaptogen stack including rhodiola, ashwagandha, lion\'s mane, and L-theanine. 1.9oz bottle.',
      targetProfile: 'Creamy liquid. Tan to dirty brown. Tropical fruity. pH 3.8–4.0.',
      status: 'active',
      stage: 'G3',
      priority: 'critical',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: false,
      qtpp: '1.9oz (56mL) shot. 40mg MIT + 520mg kavalactones. Full adaptogen stack. Natural formula. Shelf stable 2 years.',
      targetActives: 'Mitragynine 40mg, Kavalactones 520mg, L-Theanine, Lions Mane, Rhodiola, Ashwagandha',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-12-05T12:00:00Z',
    },
    {
      id: 'proj-6',
      projectCode: 'PRJ-2025-006',
      name: 'Trojan Horse Energy Shot',
      category: 'Non-Kratom Energy Shot',
      description: 'Caffeine-based energy shot using 165mg caffeine from guarana. Cordyceps, schisandra, rhodiola, L-theanine, and B12. No kratom. 2oz bottle.',
      targetProfile: 'Translucent liquid. Brown. Herbal aroma. pH 2.5–3.2.',
      status: 'active',
      stage: 'G4',
      priority: 'high',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '2oz (60mL) shot. 165mg caffeine from guarana. 2.4mcg Vitamin B12. Adaptogen stack. Shelf stable.',
      targetActives: 'Caffeine 165mg (from Guarana 50%), Vitamin B12 2.4mcg, Cordyceps, Schisandra, Rhodiola, L-Theanine',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-08-01T09:00:00Z',
      updatedAt: '2025-09-08T12:00:00Z',
    },
    {
      id: 'proj-7',
      projectCode: 'PRJ-2025-007',
      name: 'Strong Relief',
      category: 'Kratom Shot',
      description: '80mg MIT shot using filtered 2X base. Tea and citrus flavor profile. 8 formula revisions. Most mature product line. 1.9oz bottle.',
      targetProfile: 'Brown, translucent, semi-low viscous. Medium dark brown/amber. Herbal, tea, citrus. pH 2.0–3.0.',
      status: 'active',
      stage: 'G5',
      priority: 'critical',
      owner: 'Jonathan',
      cmo: 'Streamline',
      formulaFrozen: true,
      qtpp: '1.9oz (56mL) shot. 80mg MIT (76–88mg range). 2X filtered base. No Velcorin. Shelf stable 2 years.',
      targetActives: 'Mitragynine 80mg, 7-OH-Mitragynine non-detected',
      shelfLifeTarget: '2 years ambient',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2025-12-09T12:00:00Z',
    },
  ],

  formulations: [
    // 2X Pain Relief
    {
      id: 'form-1a',
      projectId: 'proj-1',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Original Formula',
      ingredients: [
        { id: 'f1a-i1', name: 'RO Water', supplier: 'Streamline', amount: 35.512, unit: 'g', percentage: 56.0, category: 'Base' },
        { id: 'f1a-i2', name: 'Sugar', supplier: 'Streamline', amount: 20.128, unit: 'g', percentage: 31.7, category: 'Sweetener' },
        { id: 'f1a-i3', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 5.000, unit: 'g', percentage: 7.9, category: 'Base' },
        { id: 'f1a-i4', name: '10:1 VivaZen Mix Kratom Extract (4.0-4.4%)', supplier: 'Fortress', amount: 2.005, unit: 'g', percentage: 3.2, category: 'Active' },
        { id: 'f1a-i5', name: 'Citric Acid', supplier: 'Streamline', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f1a-i6', name: 'Ginseng Extract', supplier: 'Fortress', amount: 0.460, unit: 'g', percentage: 0.7, category: 'Active' },
        { id: 'f1a-i7', name: 'Vitamin C', supplier: 'Fortress', amount: 0.140, unit: 'g', percentage: 0.2, category: 'Vitamin' },
        { id: 'f1a-i8', name: 'Magrabar Defoamer PD-3500', supplier: 'Streamline', amount: 0.005, unit: 'g', percentage: 0.01, category: 'Processing Aid' },
        { id: 'f1a-i9', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: mix glycerin and vivamix, blend until smooth (100°F). Screen at 200 mesh. Tank 2: water, citric acid, vitamin C — max 120°F. Add remaining ingredients. Velcorin at 15mg/bottle after cooling under 100°F.',
      targetProfile: 'Very chunky and thick. Dark brown to black. Very strong astringent herbal.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation. Velcorin-based preservation.',
      riskNotes: 'Velcorin shelf life only 24 hours post-addition. Too thick at this ratio.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-1b',
      projectId: 'proj-1',
      versionNumber: 2,
      versionLabel: 'v1.0',
      name: 'All-Natural Formula (Rev 3)',
      ingredients: [
        { id: 'f1b-i1', name: 'RO Water', supplier: 'Streamline', amount: 35.512, unit: 'g', percentage: 56.0, category: 'Base' },
        { id: 'f1b-i2', name: 'Sugar', supplier: 'Streamline', amount: 20.128, unit: 'g', percentage: 31.7, category: 'Sweetener' },
        { id: 'f1b-i3', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 5.000, unit: 'g', percentage: 7.9, category: 'Base' },
        { id: 'f1b-i4', name: '10:1 VivaZen Mix Kratom Extract (4.0-4.4%)', supplier: 'Fortress', amount: 2.005, unit: 'g', percentage: 3.2, category: 'Active' },
        { id: 'f1b-i5', name: 'Citric Acid', supplier: 'Streamline', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f1b-i6', name: 'Ginseng Extract', supplier: 'Fortress', amount: 0.460, unit: 'g', percentage: 0.7, category: 'Active' },
        { id: 'f1b-i7', name: 'Vitamin C', supplier: 'Fortress', amount: 0.140, unit: 'g', percentage: 0.2, category: 'Vitamin' },
        { id: 'f1b-i8', name: 'Magrabar Defoamer PD-3500', supplier: 'Streamline', amount: 0.005, unit: 'g', percentage: 0.01, category: 'Processing Aid' },
        { id: 'f1b-i9', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: mix glycerin and kratom extract until smooth (100°F). Screen at 200 mesh. Tank 2: water, citric acid, vitamin C — max 120°F. Combine and add remaining ingredients. Velcorin at 15mg/bottle at fill.',
      targetProfile: 'Very chunky and thick. Dark brown to black. Very strong astringent herbal. pH target 2.7.',
      status: 'approved',
      frozen: true,
      parentId: 'form-1a',
      changeLog: 'Rev 3: converted to all-natural preservative system. Updated manufacturing instructions.',
      labelImpact: 'None — same label claim. All-natural declaration eligible.',
      createdAt: '2025-03-11T12:00:00Z',
      createdBy: 'Michael Pugh',
    },

    // Energy & Focus
    {
      id: 'form-2a',
      projectId: 'proj-2',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Initial Formula',
      ingredients: [
        { id: 'f2a-i1', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Base' },
        { id: 'f2a-i2', name: 'Sugar', supplier: 'Streamline', amount: 20.000, unit: 'g', percentage: 30.5, category: 'Sweetener' },
        { id: 'f2a-i3', name: '10:1 Extract BASE', supplier: 'Streamline', amount: 40.000, unit: 'g', percentage: 61.0, category: 'Active' },
        { id: 'f2a-i4', name: 'Ginseng Extract', supplier: 'Fortress', amount: 0.230, unit: 'g', percentage: 0.4, category: 'Active' },
        { id: 'f2a-i5', name: 'Vitamin C', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Vitamin' },
        { id: 'f2a-i6', name: 'Magrabar Defoamer PD-3500', supplier: 'Streamline', amount: 0.005, unit: 'g', percentage: 0.01, category: 'Processing Aid' },
        { id: 'f2a-i7', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
        { id: 'f2a-i8', name: 'Valcorin', supplier: 'Streamline', amount: 0.014, unit: 'g', percentage: 0.02, category: 'Preservative' },
        { id: 'f2a-i9', name: 'Tea Flavor #M813532DD', supplier: 'Fortress', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Flavor' },
        { id: 'f2a-i10', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Masking Agent' },
        { id: 'f2a-i11', name: 'Tangerine Orange #7282035', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f2a-i12', name: 'Water', supplier: 'Streamline', amount: 4.410, unit: 'g', percentage: 6.7, category: 'Base' },
      ],
      processNotes: 'Heat base to 100–110°F. Mix remaining ingredients. Add Velcorin after cooling below 100°F at fill (15mg/bottle).',
      targetProfile: 'Thick with undissolved solids. Brown. Strong aseptic herbal. pH 2.5–3.2.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation — original base and preservative system.',
      riskNotes: 'Panel noted base flavor dominates; preservative system under review.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-2b',
      projectId: 'proj-2',
      versionNumber: 2,
      versionLabel: 'v1.0',
      name: 'All-Natural Formula (Rev 3)',
      ingredients: [
        { id: 'f2b-i1', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Base' },
        { id: 'f2b-i2', name: 'Sugar', supplier: 'Streamline', amount: 20.000, unit: 'g', percentage: 30.5, category: 'Sweetener' },
        { id: 'f2b-i3', name: '10:1 Extract BASE', supplier: 'Streamline', amount: 40.000, unit: 'g', percentage: 61.0, category: 'Active' },
        { id: 'f2b-i4', name: 'Ginseng Extract', supplier: 'Fortress', amount: 0.230, unit: 'g', percentage: 0.4, category: 'Active' },
        { id: 'f2b-i5', name: 'Vitamin C', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Vitamin' },
        { id: 'f2b-i6', name: 'Magrabar Defoamer PD-3500', supplier: 'Streamline', amount: 0.005, unit: 'g', percentage: 0.01, category: 'Processing Aid' },
        { id: 'f2b-i7', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
        { id: 'f2b-i8', name: 'Tea Flavor #M813532DD', supplier: 'Fortress', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Flavor' },
        { id: 'f2b-i9', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Masking Agent' },
        { id: 'f2b-i10', name: 'Tangerine Orange #7282035', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f2b-i11', name: 'Water', supplier: 'Streamline', amount: 4.410, unit: 'g', percentage: 6.7, category: 'Base' },
      ],
      processNotes: 'Heat base to 100–110°F. Mix remaining ingredients. Velcorin 15mg/bottle at fill after cooling below 100°F.',
      targetProfile: 'Thick with undissolved solids. Brown. Strong aseptic herbal. pH target 2.7.',
      status: 'approved',
      frozen: true,
      parentId: 'form-2a',
      changeLog: 'Rev 3: all-natural formula. Removed PEG-based ingredients. Nagardo as primary preservative.',
      labelImpact: 'All-natural claim now supportable. Label update required to remove Valcorin.',
      createdAt: '2025-03-11T12:00:00Z',
      createdBy: 'Michael Pugh',
    },

    // Relax & Unwind
    {
      id: 'form-3a',
      projectId: 'proj-3',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Initial Kava Formula',
      ingredients: [
        { id: 'f3a-i1', name: 'Water', supplier: 'Streamline', amount: 53.100, unit: 'g', percentage: 87.2, category: 'Base' },
        { id: 'f3a-i2', name: 'Kava Kava Extract 30%', supplier: 'Fortress', amount: 1.740, unit: 'g', percentage: 2.9, category: 'Active' },
        { id: 'f3a-i3', name: 'GABA', supplier: 'Fortress', amount: 0.600, unit: 'g', percentage: 1.0, category: 'Active' },
        { id: 'f3a-i4', name: 'Rhodiola Rosea Root Extract', supplier: 'Fortress', amount: 0.030, unit: 'g', percentage: 0.05, category: 'Active' },
        { id: 'f3a-i5', name: 'Withania Somnifera Root Extract', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f3a-i6', name: 'Eleutherococcus Senticosus Root Extract', supplier: 'Fortress', amount: 0.020, unit: 'g', percentage: 0.03, category: 'Active' },
        { id: 'f3a-i7', name: 'Schisandra Berry Extract', supplier: 'Fortress', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Active' },
        { id: 'f3a-i8', name: 'Holy Basil Leaf Extract', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.07, category: 'Active' },
        { id: 'f3a-i9', name: 'Panax Ginseng Root Extract', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f3a-i10', name: 'Sugar', supplier: 'Streamline', amount: 4.000, unit: 'g', percentage: 6.6, category: 'Sweetener' },
        { id: 'f3a-i11', name: 'Monk Fruit 50%', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Sweetener' },
        { id: 'f3a-i12', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Sweetener' },
        { id: 'f3a-i13', name: 'Citric Acid', supplier: 'Streamline', amount: 0.400, unit: 'g', percentage: 0.7, category: 'Acidulant' },
        { id: 'f3a-i14', name: 'Natural Raspberry FL #7282010', supplier: 'Fortress', amount: 0.350, unit: 'g', percentage: 0.6, category: 'Flavor' },
        { id: 'f3a-i15', name: 'Natural Lemon FL WONF #7282011', supplier: 'Fortress', amount: 0.079, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f3a-i16', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: water + citric acid, heat to max 140°F. Mix in kava 30% extract. Add remaining ingredients while blending. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Yellow, translucent. Medium yellow. Herbal, kava. pH 3.5–4.0.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation.',
      riskNotes: 'Velcorin dependency; formula to be converted to natural preservation.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-3b',
      projectId: 'proj-3',
      versionNumber: 2,
      versionLabel: 'v1.0',
      name: 'Natural Kava Formula (Rev 2)',
      ingredients: [
        { id: 'f3b-i1', name: 'Water', supplier: 'Streamline', amount: 53.100, unit: 'g', percentage: 87.2, category: 'Base' },
        { id: 'f3b-i2', name: 'Kava Kava Extract 30%', supplier: 'Fortress', amount: 1.740, unit: 'g', percentage: 2.9, category: 'Active' },
        { id: 'f3b-i3', name: 'GABA', supplier: 'Fortress', amount: 0.600, unit: 'g', percentage: 1.0, category: 'Active' },
        { id: 'f3b-i4', name: 'Rhodiola Rosea Root Extract', supplier: 'Fortress', amount: 0.030, unit: 'g', percentage: 0.05, category: 'Active' },
        { id: 'f3b-i5', name: 'Withania Somnifera Root Extract', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f3b-i6', name: 'Eleutherococcus Senticosus Root Extract', supplier: 'Fortress', amount: 0.020, unit: 'g', percentage: 0.03, category: 'Active' },
        { id: 'f3b-i7', name: 'Schisandra Berry Extract', supplier: 'Fortress', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Active' },
        { id: 'f3b-i8', name: 'Holy Basil Leaf Extract', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.07, category: 'Active' },
        { id: 'f3b-i9', name: 'Panax Ginseng Root Extract', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f3b-i10', name: 'Sugar', supplier: 'Streamline', amount: 4.000, unit: 'g', percentage: 6.6, category: 'Sweetener' },
        { id: 'f3b-i11', name: 'Monk Fruit 50%', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Sweetener' },
        { id: 'f3b-i12', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Sweetener' },
        { id: 'f3b-i13', name: 'Citric Acid', supplier: 'Streamline', amount: 0.400, unit: 'g', percentage: 0.7, category: 'Acidulant' },
        { id: 'f3b-i14', name: 'Natural Raspberry FL #7282010', supplier: 'Fortress', amount: 0.350, unit: 'g', percentage: 0.6, category: 'Flavor' },
        { id: 'f3b-i15', name: 'Natural Lemon FL WONF #7282011', supplier: 'Fortress', amount: 0.079, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f3b-i16', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: water + citric acid, heat to max 140°F. Mix in kava 30% extract with constant stirring. Add all other ingredients while blending. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Yellow, translucent. Medium yellow. Herbal, kava. pH target 3.9.',
      status: 'approved',
      frozen: true,
      parentId: 'form-3a',
      changeLog: 'Rev 2: all-natural formula conversion. Nagardo preservative system confirmed stable.',
      labelImpact: 'All-natural declaration confirmed. No label claims changed.',
      createdAt: '2025-03-12T12:00:00Z',
      createdBy: 'Michael Pugh',
    },

    // Natural Energy
    {
      id: 'form-4a',
      projectId: 'proj-4',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Initial Formula',
      ingredients: [
        { id: 'f4a-i1', name: 'Water', supplier: 'Streamline', amount: 49.374, unit: 'g', percentage: 80.8, category: 'Base' },
        { id: 'f4a-i2', name: 'Strategic 2.0 Kratom Extract 40-44%', supplier: 'Fortress', amount: 0.050, unit: 'g', percentage: 0.08, category: 'Active' },
        { id: 'f4a-i3', name: 'Vitamin B12 (Methylcobalamin)', supplier: 'Streamline', amount: 0.001, unit: 'g', percentage: 0.001, category: 'Vitamin' },
        { id: 'f4a-i4', name: 'Allulose', supplier: 'Streamline', amount: 4.900, unit: 'g', percentage: 8.0, category: 'Sweetener' },
        { id: 'f4a-i5', name: 'Natural Tangerine Orange FL #7282035', supplier: 'Fortress', amount: 0.440, unit: 'g', percentage: 0.7, category: 'Flavor' },
        { id: 'f4a-i6', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.110, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f4a-i7', name: 'Erythritol and Monk Fruit Blend', supplier: 'Fortress', amount: 4.400, unit: 'g', percentage: 7.2, category: 'Sweetener' },
        { id: 'f4a-i8', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Sweetener' },
        { id: 'f4a-i9', name: 'Natural Pineapple Flavor #7282021', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f4a-i10', name: 'Chromium Picolinate', supplier: 'Streamline', amount: 0.001, unit: 'g', percentage: 0.001, category: 'Mineral' },
        { id: 'f4a-i11', name: 'L-Carnitine', supplier: 'Streamline', amount: 0.500, unit: 'g', percentage: 0.8, category: 'Active' },
        { id: 'f4a-i12', name: 'Cordyceps Extract 40%', supplier: 'Fortress', amount: 0.188, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f4a-i13', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 0.360, unit: 'g', percentage: 0.6, category: 'Base' },
        { id: 'f4a-i14', name: 'Citric Acid', supplier: 'Streamline', amount: 0.125, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f4a-i15', name: 'Sodium Chloride', supplier: 'Streamline', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Mineral' },
        { id: 'f4a-i16', name: 'Malic Acid', supplier: 'Streamline', amount: 0.110, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f4a-i17', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
        { id: 'f4a-i18', name: 'Ethyl Alcohol', supplier: 'Streamline', amount: 0.305, unit: 'g', percentage: 0.5, category: 'Solvent' },
      ],
      processNotes: 'Blend alcohol and kratom extract until dissolved (100°F). Heat 75% water with citric and malic acid to 140°F, blend in kratom mixture. Add remaining ingredients. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Translucent, no solids. Tan to dirty brown. Tropical fruity. pH 3.5.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation.',
      riskNotes: 'Flavor masking insufficient for 40-44% extract. Needs stronger bitter blocker strategy.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-4b',
      projectId: 'proj-4',
      versionNumber: 4,
      versionLabel: 'v1.0',
      name: 'All-Natural + Water Dilution Process (Rev 4)',
      ingredients: [
        { id: 'f4b-i1', name: 'Water', supplier: 'Streamline', amount: 49.374, unit: 'g', percentage: 80.8, category: 'Base' },
        { id: 'f4b-i2', name: 'Strategic 2.0 Kratom Extract 40-44%', supplier: 'Fortress', amount: 0.050, unit: 'g', percentage: 0.08, category: 'Active' },
        { id: 'f4b-i3', name: 'Vitamin B12 (Methylcobalamin)', supplier: 'Streamline', amount: 0.001, unit: 'g', percentage: 0.001, category: 'Vitamin' },
        { id: 'f4b-i4', name: 'Allulose', supplier: 'Streamline', amount: 4.900, unit: 'g', percentage: 8.0, category: 'Sweetener' },
        { id: 'f4b-i5', name: 'Natural Tangerine Orange FL #7282035', supplier: 'Fortress', amount: 0.440, unit: 'g', percentage: 0.7, category: 'Flavor' },
        { id: 'f4b-i6', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.110, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f4b-i7', name: 'Erythritol and Monk Fruit Blend', supplier: 'Fortress', amount: 4.400, unit: 'g', percentage: 7.2, category: 'Sweetener' },
        { id: 'f4b-i8', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Sweetener' },
        { id: 'f4b-i9', name: 'Natural Pineapple Flavor #7282021', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f4b-i10', name: 'Chromium Picolinate', supplier: 'Streamline', amount: 0.001, unit: 'g', percentage: 0.001, category: 'Mineral' },
        { id: 'f4b-i11', name: 'L-Carnitine', supplier: 'Streamline', amount: 0.500, unit: 'g', percentage: 0.8, category: 'Active' },
        { id: 'f4b-i12', name: 'Cordyceps Extract 40%', supplier: 'Fortress', amount: 0.188, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f4b-i13', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 0.360, unit: 'g', percentage: 0.6, category: 'Base' },
        { id: 'f4b-i14', name: 'Citric Acid', supplier: 'Streamline', amount: 0.125, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f4b-i15', name: 'Sodium Chloride', supplier: 'Streamline', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Mineral' },
        { id: 'f4b-i16', name: 'Malic Acid', supplier: 'Streamline', amount: 0.110, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f4b-i17', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
        { id: 'f4b-i18', name: 'Ethyl Alcohol', supplier: 'Streamline', amount: 0.305, unit: 'g', percentage: 0.5, category: 'Solvent' },
      ],
      processNotes: 'Blend alcohol and kratom extract until dissolved (100°F). Heat 75% water with citric and malic acid to 140°F; slowly blend in kratom mixture. Add remaining ingredients — liquid should be translucent, no solids. Bulk MIT test: if 18–20mg/bottle go to fill; if >20mg add water to dilute [(MIT tested/20)×100%−100%] of batch weight. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Translucent, no solids. Tan to dirty brown. Tropical fruity. pH target 3.5.',
      status: 'approved',
      frozen: true,
      parentId: 'form-4a',
      changeLog: 'Rev 4: water dilution process added for MIT accuracy. All-natural formula confirmed.',
      labelImpact: 'No label change. Dilution process is a manufacturing control, not an ingredient change.',
      createdAt: '2025-12-05T12:00:00Z',
      createdBy: 'Seven Cai',
    },

    // Stress Relief
    {
      id: 'form-5a',
      projectId: 'proj-5',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Kratom+Kava 40-44% Initial',
      ingredients: [
        { id: 'f5a-i1', name: 'Water', supplier: 'Streamline', amount: 49.000, unit: 'g', percentage: 82.3, category: 'Base' },
        { id: 'f5a-i2', name: 'Kava Kava Extract 55%', supplier: 'Fortress', amount: 0.993, unit: 'g', percentage: 1.7, category: 'Active' },
        { id: 'f5a-i3', name: 'Strategic 2.0 Kratom Extract 40-44%', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.168, category: 'Active' },
        { id: 'f5a-i4', name: 'Rhodiola Rosea Root Extract', supplier: 'Fortress', amount: 0.030, unit: 'g', percentage: 0.05, category: 'Active' },
        { id: 'f5a-i5', name: 'Withania Somnifera Root Extract', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f5a-i6', name: 'Eleutherococcus Senticosus Root Extract', supplier: 'Fortress', amount: 0.020, unit: 'g', percentage: 0.03, category: 'Active' },
        { id: 'f5a-i7', name: 'Schisandra Berry Extract', supplier: 'Fortress', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Active' },
        { id: 'f5a-i8', name: 'Holy Basil Leaf Extract', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.07, category: 'Active' },
        { id: 'f5a-i9', name: 'Panax Ginseng Root Extract', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f5a-i10', name: 'Lions Mane 10:1 Extract', supplier: 'Streamline', amount: 0.240, unit: 'g', percentage: 0.4, category: 'Active' },
        { id: 'f5a-i11', name: 'L-Theanine', supplier: 'Streamline', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f5a-i12', name: 'Vitamin D3 Cholecalciferol', supplier: 'Streamline', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Vitamin' },
        { id: 'f5a-i13', name: 'Magnesium Citrate 15%', supplier: 'Streamline', amount: 0.550, unit: 'g', percentage: 0.9, category: 'Mineral' },
        { id: 'f5a-i14', name: 'Sugar', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Sweetener' },
        { id: 'f5a-i15', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Base' },
        { id: 'f5a-i16', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.3, category: 'Sweetener' },
        { id: 'f5a-i17', name: 'Monk Fruit 50%', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Sweetener' },
        { id: 'f5a-i18', name: 'Citric Acid', supplier: 'Streamline', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Acidulant' },
        { id: 'f5a-i19', name: 'Ethyl Alcohol', supplier: 'Streamline', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Solvent' },
        { id: 'f5a-i20', name: 'Natural Orange Flavor #7282022', supplier: 'Fortress', amount: 0.600, unit: 'g', percentage: 1.0, category: 'Flavor' },
        { id: 'f5a-i21', name: 'Pineapple Flavor #7282021', supplier: 'Fortress', amount: 0.400, unit: 'g', percentage: 0.7, category: 'Flavor' },
        { id: 'f5a-i22', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Masking Agent' },
        { id: 'f5a-i23', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: mix Strategic extract 2.0 with alcohol, warm to dissolve. Tank 2: water + citric acid, max 140°F. Add tank 1 slowly. Add kava 55% while water warm. Add remaining ingredients except Velcorin. Bulk MIT test before fill. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Creamy liquid. Tan to dirty brown. Tropical fruity. pH 3.85.',
      status: 'in-testing',
      frozen: false,
      changeLog: 'Initial creation. Dual-active Kratom+Kava formula.',
      riskNotes: 'Kavalactone-kratom interaction profile under evaluation. MIT dilution process needed.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-5b',
      projectId: 'proj-5',
      versionNumber: 3,
      versionLabel: 'v0.3',
      name: 'Kratom+Kava 40-44% with Water Dilution (Rev 3)',
      ingredients: [
        { id: 'f5b-i1', name: 'Water', supplier: 'Streamline', amount: 49.000, unit: 'g', percentage: 82.3, category: 'Base' },
        { id: 'f5b-i2', name: 'Kava Kava Extract 55%', supplier: 'Fortress', amount: 0.993, unit: 'g', percentage: 1.7, category: 'Active' },
        { id: 'f5b-i3', name: 'Strategic 2.0 Kratom Extract 40-44%', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.168, category: 'Active' },
        { id: 'f5b-i4', name: 'Rhodiola Rosea Root Extract', supplier: 'Fortress', amount: 0.030, unit: 'g', percentage: 0.05, category: 'Active' },
        { id: 'f5b-i5', name: 'Withania Somnifera Root Extract', supplier: 'Fortress', amount: 0.060, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f5b-i6', name: 'Eleutherococcus Senticosus Root Extract', supplier: 'Fortress', amount: 0.020, unit: 'g', percentage: 0.03, category: 'Active' },
        { id: 'f5b-i7', name: 'Schisandra Berry Extract', supplier: 'Fortress', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Active' },
        { id: 'f5b-i8', name: 'Holy Basil Leaf Extract', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.07, category: 'Active' },
        { id: 'f5b-i9', name: 'Panax Ginseng Root Extract', supplier: 'Fortress', amount: 0.070, unit: 'g', percentage: 0.1, category: 'Active' },
        { id: 'f5b-i10', name: 'Lions Mane 10:1 Extract', supplier: 'Streamline', amount: 0.240, unit: 'g', percentage: 0.4, category: 'Active' },
        { id: 'f5b-i11', name: 'L-Theanine', supplier: 'Streamline', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f5b-i12', name: 'Vitamin D3 Cholecalciferol', supplier: 'Streamline', amount: 0.010, unit: 'g', percentage: 0.02, category: 'Vitamin' },
        { id: 'f5b-i13', name: 'Magnesium Citrate 15%', supplier: 'Streamline', amount: 0.550, unit: 'g', percentage: 0.9, category: 'Mineral' },
        { id: 'f5b-i14', name: 'Sugar', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Sweetener' },
        { id: 'f5b-i15', name: 'Vegetable Glycerin', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Base' },
        { id: 'f5b-i16', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.3, category: 'Sweetener' },
        { id: 'f5b-i17', name: 'Monk Fruit 50%', supplier: 'Streamline', amount: 0.250, unit: 'g', percentage: 0.4, category: 'Sweetener' },
        { id: 'f5b-i18', name: 'Citric Acid', supplier: 'Streamline', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Acidulant' },
        { id: 'f5b-i19', name: 'Ethyl Alcohol', supplier: 'Streamline', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Solvent' },
        { id: 'f5b-i20', name: 'Natural Orange Flavor #7282022', supplier: 'Fortress', amount: 0.600, unit: 'g', percentage: 1.0, category: 'Flavor' },
        { id: 'f5b-i21', name: 'Pineapple Flavor #7282021', supplier: 'Fortress', amount: 0.400, unit: 'g', percentage: 0.7, category: 'Flavor' },
        { id: 'f5b-i22', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Masking Agent' },
        { id: 'f5b-i23', name: 'Nagardo', supplier: 'Streamline', amount: 0.012, unit: 'g', percentage: 0.02, category: 'Preservative' },
      ],
      processNotes: 'Tank 1: Strategic 2.0 + alcohol, warm to dissolve until translucent. Tank 2: water + citric acid, max 140°F; add Tank 1 slowly — no precipitate. Add kava 55% while warm. Add all except Velcorin. Bulk MIT test: if 38–40mg go to fill; if >40mg add water to dilute [(MIT tested/40)×100%−100%] of batch weight. Velcorin 15mg/bottle at fill below 100°F.',
      targetProfile: 'Creamy liquid. Tan to dirty brown. Tropical fruity. pH target 3.85.',
      status: 'in-testing',
      frozen: false,
      parentId: 'form-5a',
      changeLog: 'Rev 3: water dilution process added for MIT accuracy at fill.',
      riskNotes: '45–49% variant (VZ-STRESSRELIEF-40.45-49) in parallel development — ingredient ratios nearly identical, extract swapped.',
      createdAt: '2025-12-05T12:00:00Z',
      createdBy: 'Seven Cai',
    },

    // Trojan Horse Energy Shot
    {
      id: 'form-6a',
      projectId: 'proj-6',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Initial Energy Shot',
      ingredients: [
        { id: 'f6a-i1', name: 'Water', supplier: 'Streamline', amount: 51.199, unit: 'g', percentage: 85.3, category: 'Base' },
        { id: 'f6a-i2', name: 'Cordyceps Mycelium (Cordyceps militaris) 40%', supplier: 'Fortress', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Active' },
        { id: 'f6a-i3', name: 'Schisandra Fruit Extract', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Active' },
        { id: 'f6a-i4', name: 'L-Theanine', supplier: 'Streamline', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Active' },
        { id: 'f6a-i5', name: 'Guarana Seed Extract 50% Caffeine', supplier: 'Fortress', amount: 0.347, unit: 'g', percentage: 0.6, category: 'Active' },
        { id: 'f6a-i6', name: 'Rhodiola Root Extract', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f6a-i7', name: 'Vitamin B12 99%', supplier: 'Streamline', amount: 0.000003, unit: 'g', percentage: 0.000005, category: 'Vitamin' },
        { id: 'f6a-i8', name: 'Velcorin', supplier: 'Streamline', amount: 0.015, unit: 'g', percentage: 0.025, category: 'Preservative' },
        { id: 'f6a-i9', name: 'Caffeine Modifier #M397139H', supplier: 'Fortress', amount: 0.080, unit: 'g', percentage: 0.1, category: 'Masking Agent' },
        { id: 'f6a-i10', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f6a-i11', name: 'Orange Pineapple Guava #7282004', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Flavor' },
        { id: 'f6a-i12', name: 'Mango Flavor #7282008', supplier: 'Fortress', amount: 0.050, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f6a-i13', name: 'Sugar', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Sweetener' },
        { id: 'f6a-i14', name: 'Nagardo', supplier: 'Streamline', amount: 0.015, unit: 'g', percentage: 0.025, category: 'Preservative' },
        { id: 'f6a-i15', name: 'Erythritol', supplier: 'Streamline', amount: 4.000, unit: 'g', percentage: 6.7, category: 'Sweetener' },
        { id: 'f6a-i16', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.025, unit: 'g', percentage: 0.04, category: 'Sweetener' },
        { id: 'f6a-i17', name: 'Citric Acid', supplier: 'Streamline', amount: 0.120, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f6a-i18', name: 'Malic Acid', supplier: 'Streamline', amount: 0.050, unit: 'g', percentage: 0.1, category: 'Acidulant' },
      ],
      processNotes: 'Tank 1: water + acids, warm to 100–120°F. Add all ingredients except 4 flavors. Heat to 140°F until dissolved. Cool to ~110°F. Add flavors. Fill with 15mg Velcorin per bottle.',
      targetProfile: 'Translucent liquid. Brown. Herbal. pH target 2.9.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation. Caffeine overage not yet applied.',
      riskNotes: 'Caffeine level slightly below claim target under HPLC testing. Overage needed.',
      createdAt: '2025-08-11T09:00:00Z',
      createdBy: 'Seven Cai',
    },
    {
      id: 'form-6b',
      projectId: 'proj-6',
      versionNumber: 3,
      versionLabel: 'v1.0',
      name: 'Final Formula with Caffeine Overage (Rev 3)',
      ingredients: [
        { id: 'f6b-i1', name: 'Water', supplier: 'Streamline', amount: 51.199, unit: 'g', percentage: 85.3, category: 'Base' },
        { id: 'f6b-i2', name: 'Cordyceps Mycelium (Cordyceps militaris) 40%', supplier: 'Fortress', amount: 0.300, unit: 'g', percentage: 0.5, category: 'Active' },
        { id: 'f6b-i3', name: 'Schisandra Fruit Extract', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Active' },
        { id: 'f6b-i4', name: 'L-Theanine', supplier: 'Streamline', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Active' },
        { id: 'f6b-i5', name: 'Guarana Seed Extract 50% Caffeine', supplier: 'Fortress', amount: 0.347, unit: 'g', percentage: 0.6, category: 'Active' },
        { id: 'f6b-i6', name: 'Rhodiola Root Extract', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Active' },
        { id: 'f6b-i7', name: 'Vitamin B12 99%', supplier: 'Streamline', amount: 0.000003, unit: 'g', percentage: 0.000005, category: 'Vitamin' },
        { id: 'f6b-i8', name: 'Velcorin', supplier: 'Streamline', amount: 0.015, unit: 'g', percentage: 0.025, category: 'Preservative' },
        { id: 'f6b-i9', name: 'Caffeine Modifier #M397139H', supplier: 'Fortress', amount: 0.080, unit: 'g', percentage: 0.1, category: 'Masking Agent' },
        { id: 'f6b-i10', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f6b-i11', name: 'Orange Pineapple Guava #7282004', supplier: 'Fortress', amount: 0.200, unit: 'g', percentage: 0.3, category: 'Flavor' },
        { id: 'f6b-i12', name: 'Mango Flavor #7282008', supplier: 'Fortress', amount: 0.050, unit: 'g', percentage: 0.1, category: 'Flavor' },
        { id: 'f6b-i13', name: 'Sugar', supplier: 'Streamline', amount: 3.000, unit: 'g', percentage: 5.0, category: 'Sweetener' },
        { id: 'f6b-i14', name: 'Nagardo', supplier: 'Streamline', amount: 0.015, unit: 'g', percentage: 0.025, category: 'Preservative' },
        { id: 'f6b-i15', name: 'Erythritol', supplier: 'Streamline', amount: 4.000, unit: 'g', percentage: 6.7, category: 'Sweetener' },
        { id: 'f6b-i16', name: 'Stevia REB M', supplier: 'Fortress', amount: 0.025, unit: 'g', percentage: 0.04, category: 'Sweetener' },
        { id: 'f6b-i17', name: 'Citric Acid', supplier: 'Streamline', amount: 0.120, unit: 'g', percentage: 0.2, category: 'Acidulant' },
        { id: 'f6b-i18', name: 'Malic Acid', supplier: 'Streamline', amount: 0.050, unit: 'g', percentage: 0.1, category: 'Acidulant' },
      ],
      processNotes: 'Tank 1: water + acids, warm to 100–120°F. Add all ingredients except 4 flavors (Caffeine Modifier, Bitter Blocker, OPG, Mango). Heat to 140°F until dissolved. Cool to ~110°F. Add flavors. Fill with 15mg Velcorin per bottle.',
      targetProfile: 'Translucent liquid. Brown. Herbal. pH target 2.9.',
      status: 'approved',
      frozen: true,
      parentId: 'form-6a',
      changeLog: 'Rev 3: caffeine overage added to hit 165mg claim under HPLC. Formula locked.',
      labelImpact: 'Caffeine claim updated on label to 165mg. UPC 628504926291.',
      createdAt: '2025-09-08T12:00:00Z',
      createdBy: 'Seven Cai',
    },

    // Strong Relief
    {
      id: 'form-7a',
      projectId: 'proj-7',
      versionNumber: 1,
      versionLabel: 'v0.1',
      name: 'Initial Strong Formula',
      ingredients: [
        { id: 'f7a-i1', name: 'Sugar', supplier: 'Streamline', amount: 20.000, unit: 'g', percentage: 31.3, category: 'Sweetener' },
        { id: 'f7a-i2', name: '2X Base (50/50)', supplier: 'Fortress', amount: 40.000, unit: 'g', percentage: 62.5, category: 'Active' },
        { id: 'f7a-i3', name: 'Tea Flavor #M813532DD', supplier: 'Fortress', amount: 0.400, unit: 'g', percentage: 0.6, category: 'Flavor' },
        { id: 'f7a-i4', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f7a-i5', name: 'Sodium Chloride', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.1, category: 'Mineral' },
        { id: 'f7a-i6', name: 'Sweet Citrus Flavor #8281274U', supplier: 'Fortress', amount: 0.130, unit: 'g', percentage: 0.2, category: 'Flavor' },
        { id: 'f7a-i7', name: 'Clear Mask FM521', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f7a-i8', name: 'Water', supplier: 'Streamline', amount: 3.170, unit: 'g', percentage: 5.0, category: 'Base' },
        { id: 'f7a-i9', name: 'Nagardo', supplier: 'Streamline', amount: 0.010, unit: 'g', percentage: 0.016, category: 'Preservative' },
      ],
      processNotes: 'Settled tote base filtered through 250 micron tea bag. Heat base to 100–110°F. Mix remaining ingredients. Heat base to 100–110°F. Add Nagardo pre-dissolved in small water portion. Pump to sterile totes through filter.',
      targetProfile: 'Brown, translucent, semi-low viscous. Medium dark brown/amber. Herbal, tea, citrus. pH 2.0–3.0.',
      status: 'rejected',
      frozen: false,
      changeLog: 'Initial creation. Velcorin included.',
      riskNotes: 'Manufacturing process requires further refinement. Velcorin to be removed per Rev 8.',
      createdAt: '2025-01-22T10:00:00Z',
      createdBy: 'Michael Pugh',
    },
    {
      id: 'form-7b',
      projectId: 'proj-7',
      versionNumber: 8,
      versionLabel: 'v1.0',
      name: 'Final Strong Relief (Rev 8)',
      ingredients: [
        { id: 'f7b-i1', name: 'Sugar', supplier: 'Streamline', amount: 20.000, unit: 'g', percentage: 31.3, category: 'Sweetener' },
        { id: 'f7b-i2', name: '2X Base (50/50)', supplier: 'Fortress', amount: 40.000, unit: 'g', percentage: 62.5, category: 'Active' },
        { id: 'f7b-i3', name: 'Tea Flavor #M813532DD', supplier: 'Fortress', amount: 0.400, unit: 'g', percentage: 0.6, category: 'Flavor' },
        { id: 'f7b-i4', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', amount: 0.150, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f7b-i5', name: 'Sodium Chloride', supplier: 'Fortress', amount: 0.040, unit: 'g', percentage: 0.1, category: 'Mineral' },
        { id: 'f7b-i6', name: 'Sweet Citrus Flavor #8281274U', supplier: 'Fortress', amount: 0.130, unit: 'g', percentage: 0.2, category: 'Flavor' },
        { id: 'f7b-i7', name: 'Clear Mask FM521', supplier: 'Fortress', amount: 0.100, unit: 'g', percentage: 0.2, category: 'Masking Agent' },
        { id: 'f7b-i8', name: 'Water', supplier: 'Streamline', amount: 3.170, unit: 'g', percentage: 5.0, category: 'Base' },
        { id: 'f7b-i9', name: 'Nagardo', supplier: 'Streamline', amount: 0.010, unit: 'g', percentage: 0.016, category: 'Preservative' },
      ],
      processNotes: 'After settling, siphon base from top of tote to Tank 1. Concentration result: if 1.90–2.00 mg/g go directly; if >2.00 mg/g add water [(result/2)×100%−100%] of batch weight. Heat base to 100–110°F. Mix remaining ingredients. Pre-dissolve Nagardo in small water portion (min 3 min, let foam drop). Pump to sterile totes through 250 micron tea bag. No Velcorin — Nagardo only.',
      targetProfile: 'Brown, translucent, semi-low viscous. Medium dark brown/amber. Herbal, tea, citrus. pH target 2.0.',
      status: 'approved',
      frozen: true,
      parentId: 'form-7a',
      changeLog: 'Rev 8: Velcorin removed. Sugar and Nagardo levels adjusted. Nagardo-only preservation confirmed stable. SKU FIN10656.',
      labelImpact: 'Velcorin removed from ingredient label. All-natural declaration. UPC 609465000022.',
      createdAt: '2025-12-09T12:00:00Z',
      createdBy: 'Seven Cai',
    },
  ],

  samples: [
    {
      id: 'samp-1',
      formulationId: 'form-5b',
      projectId: 'proj-5',
      batchCode: 'SR-2026-001',
      rsln: 'RDS-260115-SL-IN-001',
      sampleClass: 'A',
      lifecycleStatus: 'consumed',
      dateProduced: '2026-01-15',
      quantity: 24,
      quantityUnit: 'bottles',
      recipients: [
        { id: 'r1', name: 'Jonathan', role: 'R&D Lead', dateSent: '2026-01-16', feedbackReceived: true },
        { id: 'r2', name: 'Michael Pugh', role: 'Formulator', dateSent: '2026-01-16', feedbackReceived: true },
      ],
      status: 'feedback-complete',
      intendedUse: 'Internal sensory — R&D evaluation of dual-active kratom+kava profile',
      storageCondition: 'Room temp, cool dry place',
      site: 'SL',
      externalDistribution: false,
      ingestionPossible: true,
      notes: 'First batch of Rev 3 formula with water dilution process. MIT bulk test confirmed 39.8mg/bottle.',
      expiryDate: '2028-01-15',
    },
    {
      id: 'samp-2',
      formulationId: 'form-4b',
      projectId: 'proj-4',
      batchCode: 'NE-2026-001',
      rsln: 'RDS-260210-SL-IN-002',
      sampleClass: 'B',
      lifecycleStatus: 'released',
      dateProduced: '2026-02-10',
      quantity: 48,
      quantityUnit: 'bottles',
      recipients: [
        { id: 'r3', name: 'Jonathan', role: 'R&D Lead', dateSent: '2026-02-11', feedbackReceived: true },
        { id: 'r4', name: 'Sales Team', role: 'Market Preview', dateSent: '2026-02-14', feedbackReceived: true },
      ],
      status: 'feedback-complete',
      intendedUse: 'Internal panel + sales team preview of Natural Energy v1.0',
      storageCondition: 'Room temp, cool dry place',
      site: 'SL',
      externalDistribution: false,
      ingestionPossible: true,
      notes: 'Rev 4 final formula. MIT confirmed 19.6mg/bottle (within 18–24mg range). Panel approved for freeze.',
      expiryDate: '2028-02-10',
    },
    {
      id: 'samp-3',
      formulationId: 'form-6b',
      projectId: 'proj-6',
      batchCode: 'TH-2025-001',
      rsln: 'RDS-250915-SL-EX-001',
      sampleClass: 'B',
      lifecycleStatus: 'at-recipient',
      dateProduced: '2025-09-15',
      quantity: 60,
      quantityUnit: 'bottles',
      recipients: [
        { id: 'r5', name: 'Retail Partner A', role: 'Buyer', dateSent: '2025-09-18', feedbackReceived: true },
        { id: 'r6', name: 'Jonathan', role: 'R&D Lead', dateSent: '2025-09-15', feedbackReceived: true },
      ],
      status: 'feedback-complete',
      intendedUse: 'External buyer preview — Trojan Horse Energy Shot market validation',
      storageCondition: 'Room temp, cool dry place',
      site: 'SL',
      externalDistribution: true,
      ingestionPossible: true,
      notes: 'Post-freeze pilot run. Caffeine HPLC confirmed 163mg/bottle. Buyer approved for PO.',
      expiryDate: '2027-09-15',
    },
    {
      id: 'samp-4',
      formulationId: 'form-7b',
      projectId: 'proj-7',
      batchCode: 'STRNG-2026-001',
      rsln: 'RDS-260321-SL-IN-003',
      sampleClass: 'A',
      lifecycleStatus: 'in-storage',
      dateProduced: '2026-03-21',
      quantity: 24,
      quantityUnit: 'bottles',
      recipients: [
        { id: 'r7', name: 'Jonathan', role: 'R&D Lead', dateSent: '2026-03-21', feedbackReceived: false },
        { id: 'r8', name: 'QA Team', role: 'Release Testing', dateSent: '2026-03-22', feedbackReceived: false },
      ],
      status: 'in-review',
      intendedUse: 'Stability check at T=3 months. Rev 8 Nagardo-only preservation validation.',
      storageCondition: 'Room temp, cool dry place',
      site: 'SL',
      externalDistribution: false,
      ingestionPossible: true,
      notes: 'Stability pull for 3-month time point. Microbio and MIT to be confirmed.',
      expiryDate: '2028-03-21',
    },
  ],

  feedback: [
    {
      id: 'fb-1',
      sampleId: 'samp-1',
      formulationId: 'form-5b',
      projectId: 'proj-5',
      reviewerName: 'Jonathan',
      reviewerRole: 'R&D Lead',
      date: '2026-01-20T10:00:00Z',
      ratings: { taste: 7, aroma: 6, appearance: 7, texture: 8, aftertaste: 6, overall: 7 },
      overallScore: 7,
      positives: 'Dual-active profile very noticeable. Tropical flavor masks well. Kava onset is smooth.',
      negatives: 'Slight bitterness at finish. Kratom earthiness still present under the orange/pineapple.',
      suggestions: 'Consider increasing bitter blocker by 10–15%. May also trial a citrus top note to cut through the herbal base.',
      recommendReformulation: false,
    },
    {
      id: 'fb-2',
      sampleId: 'samp-1',
      formulationId: 'form-5b',
      projectId: 'proj-5',
      reviewerName: 'Michael Pugh',
      reviewerRole: 'Formulator',
      date: '2026-01-20T14:00:00Z',
      ratings: { taste: 6, aroma: 7, appearance: 7, texture: 8, aftertaste: 5, overall: 6 },
      overallScore: 6,
      positives: 'pH and bottle weight on target. Kava and kratom claims confirmed analytically.',
      negatives: 'Aftertaste lingers longer than comparable 2X products. Formula not yet ready to freeze.',
      suggestions: 'Evaluate 45–49% extract variant — higher potency may allow lower extract load and cleaner taste.',
      recommendReformulation: true,
    },
    {
      id: 'fb-3',
      sampleId: 'samp-2',
      formulationId: 'form-4b',
      projectId: 'proj-4',
      reviewerName: 'Jonathan',
      reviewerRole: 'R&D Lead',
      date: '2026-02-18T11:00:00Z',
      ratings: { taste: 8, aroma: 8, appearance: 9, texture: 9, aftertaste: 8, overall: 8 },
      overallScore: 8,
      positives: 'Clean, translucent appearance. Tropical pineapple-orange profile is excellent. L-carnitine and cordyceps add functional story. No solids.',
      negatives: 'Slightly sweet — may polarize consumers who prefer dry. Chromium contribution minor; consider removal to simplify label.',
      suggestions: 'Ready to freeze at this revision. Consider reducing Stevia by 15% in next iteration for drier finish, but not blocking the freeze.',
      recommendReformulation: false,
    },
    {
      id: 'fb-4',
      sampleId: 'samp-3',
      formulationId: 'form-6b',
      projectId: 'proj-6',
      reviewerName: 'Jonathan',
      reviewerRole: 'R&D Lead',
      date: '2025-09-20T10:00:00Z',
      ratings: { taste: 8, aroma: 7, appearance: 8, texture: 9, aftertaste: 7, overall: 8 },
      overallScore: 8,
      positives: 'Caffeine onset clean and sustained. No jitteriness in panel. Mango + OPG flavor is well-balanced. Buyer positive response.',
      negatives: 'Caffeine modifier slightly detectable at room temp — less noticeable chilled.',
      suggestions: 'Formula frozen as-is. Recommend chilled consumption guidance on label. Buyer PO received.',
      recommendReformulation: false,
    },
  ],

  gateReviews: [
    // 2X Pain Relief
    { id: 'gate-1', projectId: 'proj-1', gate: 'G0', actualDate: '2025-01-10', reviewers: 'Jonathan', decision: 'GO', evidenceNotes: 'PRJ-2025-001 assigned. 80mg MIT shot concept approved. Market gap identified vs. standard 40mg products.', createdAt: '2025-01-10T09:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-2', projectId: 'proj-1', gate: 'G1', actualDate: '2025-01-20', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'QTPP defined: 80mg MIT, 1.9oz, pH 2.5–3.2, 2-year shelf life. Regulatory guardrails confirmed. 10:1 extract selected.', createdAt: '2025-01-20T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-3', projectId: 'proj-1', gate: 'G2', actualDate: '2025-02-10', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Design inputs locked. Analytical plan covers MIT, 7-OH-MIT, microbio, heavy metals. Stability strategy: real-time + accelerated.', createdAt: '2025-02-10T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-4', projectId: 'proj-1', gate: 'G3', actualDate: '2025-02-28', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'v0.1 prototype complete. MIT confirmed 78mg/bottle. Flavor and texture acceptable for internal panel.', createdAt: '2025-02-28T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-5', projectId: 'proj-1', gate: 'G4', actualDate: '2025-03-11', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Formula v1.0 frozen. All-natural Rev 3 approved. MIT 79–82mg/bottle across 3 pilot batches. Label and claims cleared.', createdAt: '2025-03-11T12:00:00Z', createdBy: 'Jonathan' },

    // Natural Energy
    { id: 'gate-6', projectId: 'proj-4', gate: 'G0', actualDate: '2025-01-10', reviewers: 'Jonathan', decision: 'GO', evidenceNotes: 'PRJ-2025-004 assigned. 20mg MIT entry-level shot concept. Target: first-time users and lower tolerance segment.', createdAt: '2025-01-10T09:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-7', projectId: 'proj-4', gate: 'G1', actualDate: '2025-01-22', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'QTPP defined: 20mg MIT, cordyceps + L-carnitine stack, tropical flavor, 1.9oz. All-natural target.', createdAt: '2025-01-22T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-8', projectId: 'proj-4', gate: 'G2', actualDate: '2025-02-15', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Design inputs approved. Allulose + erythritol sweetener system finalized. Strategic 2.0 extract selected for cleaner dissolution.', createdAt: '2025-02-15T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-9', projectId: 'proj-4', gate: 'G3', actualDate: '2025-03-20', reviewers: 'Jonathan, Michael Pugh', decision: 'GO with Conditions', conditions: 'Water dilution process must be validated before freeze. MIT analytical protocol to be updated.', conditionOwner: 'Jonathan', conditionDueDate: '2025-12-05', evidenceNotes: 'v0.3 all-natural prototype complete. Flavor profile excellent. MIT dilution process not yet validated.', createdAt: '2025-03-20T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-10', projectId: 'proj-4', gate: 'G4', actualDate: '2025-12-05', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'Formula v1.0 frozen. Water dilution process validated — MIT 19.6mg/bottle. G3 condition cleared. Label finalized. FIN10649.', createdAt: '2025-12-05T12:00:00Z', createdBy: 'Jonathan' },

    // Stress Relief
    { id: 'gate-11', projectId: 'proj-5', gate: 'G0', actualDate: '2025-01-10', reviewers: 'Jonathan', decision: 'GO', evidenceNotes: 'PRJ-2025-005 assigned. Dual-active kratom+kava concept. Target: premium relaxation + relief SKU.', createdAt: '2025-01-10T09:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-12', projectId: 'proj-5', gate: 'G1', actualDate: '2025-01-22', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'QTPP defined: 40mg MIT + 520mg kavalactones. Full adaptogen stack. 1.9oz. Regulatory: dual active requires separate COA testing.', createdAt: '2025-01-22T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-13', projectId: 'proj-5', gate: 'G2', actualDate: '2025-02-20', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Design inputs locked. Dual-extract analytical plan. Kava 55% selected for kavalactone density.', createdAt: '2025-02-20T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-14', projectId: 'proj-5', gate: 'G3', actualDate: '2026-01-15', reviewers: 'Jonathan, Michael Pugh, Seven Cai', decision: 'GO with Conditions', conditions: 'Formula freeze pending 45-49% extract variant evaluation. Water dilution process validation required.', conditionOwner: 'Jonathan', conditionDueDate: '2026-06-30', evidenceNotes: 'v0.3 internal sensory complete. MIT 39.8mg and kavalactones 518mg confirmed analytically. Flavor needs minor tuning. 45-49% variant initiated.', createdAt: '2026-01-15T12:00:00Z', createdBy: 'Jonathan' },

    // Trojan Horse Energy Shot
    { id: 'gate-15', projectId: 'proj-6', gate: 'G0', actualDate: '2025-08-01', reviewers: 'Jonathan', decision: 'GO', evidenceNotes: 'PRJ-2025-006 assigned. Non-kratom energy shot concept for broader retail channels. Guarana-based caffeine.', createdAt: '2025-08-01T09:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-16', projectId: 'proj-6', gate: 'G1', actualDate: '2025-08-11', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'QTPP: 165mg caffeine, 2.4mcg B12, adaptogen stack. 2oz. No kratom — opens mass retail channels.', createdAt: '2025-08-11T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-17', projectId: 'proj-6', gate: 'G2', actualDate: '2025-08-20', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'Design inputs finalized. Guarana 50% caffeine selected as primary active. HPLC caffeine method established.', createdAt: '2025-08-20T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-18', projectId: 'proj-6', gate: 'G3', actualDate: '2025-09-01', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'v0.2 prototype acceptable. Caffeine overage strategy defined. Flavor profile approved by internal panel.', createdAt: '2025-09-01T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-19', projectId: 'proj-6', gate: 'G4', actualDate: '2025-09-08', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'Formula v1.0 frozen. Rev 3 caffeine overage confirmed 163mg/bottle (target 165mg, range accepted). Buyer preview positive. FIN10653.', createdAt: '2025-09-08T12:00:00Z', createdBy: 'Jonathan' },

    // Strong Relief
    { id: 'gate-20', projectId: 'proj-7', gate: 'G0', actualDate: '2025-01-10', reviewers: 'Jonathan', decision: 'GO', evidenceNotes: 'PRJ-2025-007 assigned. 80mg MIT filtered extract shot. 2X base filtration process — cleaner, more consistent MIT delivery.', createdAt: '2025-01-10T09:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-21', projectId: 'proj-7', gate: 'G1', actualDate: '2025-01-22', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'QTPP defined: 80mg MIT, filtered 2X base, tea+citrus flavor, pH 2.0–3.0. No 7-OH-MIT detected target.', createdAt: '2025-01-22T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-22', projectId: 'proj-7', gate: 'G2', actualDate: '2025-02-10', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Design inputs locked. Siphon + 250 micron tea bag filtration process defined. Tea + citrus masking system selected.', createdAt: '2025-02-10T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-23', projectId: 'proj-7', gate: 'G3', actualDate: '2025-04-15', reviewers: 'Jonathan, Michael Pugh', decision: 'GO', evidenceNotes: 'Prototype series complete (Revs 1–4). 2X extract base validated. Clear Mask FM521 added for improved flavor.', createdAt: '2025-04-15T10:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-24', projectId: 'proj-7', gate: 'G4', actualDate: '2025-12-09', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'Formula v1.0 (Rev 8) frozen. Velcorin removed. Nagardo-only confirmed stable. MIT 78–82mg across 5 batches. FIN10656.', createdAt: '2025-12-09T12:00:00Z', createdBy: 'Jonathan' },
    { id: 'gate-25', projectId: 'proj-7', gate: 'G5', actualDate: '2026-02-01', reviewers: 'Jonathan, Seven Cai', decision: 'GO', evidenceNotes: 'Commercial-scale pilot complete. MMR transferred to Streamline. Stability initiated. 3-month pull scheduled for April 2026.', createdAt: '2026-02-01T12:00:00Z', createdBy: 'Jonathan' },
  ],

  materials: [
    { id: 'mat-1', materialCode: 'MAT-0001', name: 'Strategic 2.0 Kratom Extract 40-44%', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'MIT content 40-44%. Full COA including MIT, 7-OH-MIT, heavy metals, microbio. Supplier qualified.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-2', materialCode: 'MAT-0002', name: 'Strategic 2.0 Kratom Extract 45-49%', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'MIT content 45-49%. Higher potency variant — allows lower extract load per bottle.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-3', materialCode: 'MAT-0003', name: '10:1 VivaZen Mix Kratom Extract (4.0-4.4%)', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: '10:1 powdered extract, 4.0-4.4% MIT. Used in 2X Pain Relief and Energy & Focus as base extract.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-4', materialCode: 'MAT-0004', name: 'Kava Kava Extract 55%', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: '55% kavalactone content. Used in Stress Relief for dual-active profile.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-5', materialCode: 'MAT-0005', name: 'Kava Kava Extract 30%', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: '30% kavalactone content. Used in Relax & Unwind. Milder kava profile.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-6', materialCode: 'MAT-0006', name: '2X Base (50/50 Filtered Extract)', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Filtered and concentrated 2X kratom base. ~2.0 mg/g MIT. Used exclusively in Strong Relief. Requires 250 micron filter at fill.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-7', materialCode: 'MAT-0007', name: 'Guarana Seed Extract 50% Caffeine', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: '50% caffeine from Paullinia cupana. Used in Trojan Horse. HPLC caffeine method established.', lastUpdated: '2025-08-01T09:00:00Z' },
    { id: 'mat-8', materialCode: 'MAT-0008', name: 'Cordyceps Mycelium Extract 40%', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Cordyceps militaris. 40% polysaccharides. Used in Natural Energy and Trojan Horse.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-9', materialCode: 'MAT-0009', name: 'L-Theanine', supplier: 'Streamline', category: 'Active / Amino Acid', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'USP grade. Used in Stress Relief and Trojan Horse. Third-party tested.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-10', materialCode: 'MAT-0010', name: 'L-Carnitine', supplier: 'Streamline', category: 'Active / Amino Acid', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'L-Carnitine tartrate. Used in Natural Energy functional stack.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-11', materialCode: 'MAT-0011', name: 'GABA', supplier: 'Fortress', category: 'Active / Amino Acid', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Gamma-aminobutyric acid. 300mg per bottle in Relax & Unwind.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-12', materialCode: 'MAT-0012', name: 'Lions Mane 10:1 Extract', supplier: 'Streamline', category: 'Active / Botanical', coaStatus: 'received', rdApproved: true, commercialReady: false, notes: 'Hericium erinaceus 10:1. Used in Stress Relief. Commercial supplier qualification in progress.', lastUpdated: '2025-12-01T09:00:00Z' },
    { id: 'mat-13', materialCode: 'MAT-0013', name: 'Rhodiola Rosea Root Extract', supplier: 'Fortress', category: 'Active / Botanical', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Used in Stress Relief, Relax & Unwind, and Trojan Horse adaptogen stacks.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-14', materialCode: 'MAT-0014', name: 'Nagardo', supplier: 'Streamline', category: 'Preservative', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'All-natural preservation system. Used across all current formulas. Effective at trace levels (0.012–0.015g/bottle).', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-15', materialCode: 'MAT-0015', name: 'Sensapure Bitter Blocker #7282001', supplier: 'Fortress', category: 'Masking Agent', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Core bitter masking agent across all kratom formulas. Critical for palatability.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-16', materialCode: 'MAT-0016', name: 'Clear Mask FM521', supplier: 'Fortress', category: 'Masking Agent', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Added in Strong Relief Rev 6. Pairs with Bitter Blocker for improved flavor in filtered extract base.', lastUpdated: '2025-09-25T09:00:00Z' },
    { id: 'mat-17', materialCode: 'MAT-0017', name: 'Natural Orange Flavor #7282022', supplier: 'Fortress', category: 'Flavor', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Primary citrus flavor in Stress Relief. Natural WONF.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-18', materialCode: 'MAT-0018', name: 'Natural Pineapple Flavor #7282021', supplier: 'Fortress', category: 'Flavor', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Secondary tropical flavor in Natural Energy and Stress Relief.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-19', materialCode: 'MAT-0019', name: 'Tea Flavor #M813532DD', supplier: 'Flavor Producers', category: 'Flavor', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Primary flavor in Strong Relief and Energy & Focus. Herbal/tea profile.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-20', materialCode: 'MAT-0020', name: 'Allulose', supplier: 'Streamline', category: 'Sweetener', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Rare sugar, 0 net carbs. Used in Natural Energy for clean sweetness without glycemic impact.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-21', materialCode: 'MAT-0021', name: 'Stevia REB M', supplier: 'Fortress', category: 'Sweetener', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'High-purity rebaudioside M. Used across multiple formulas. Lower bitterness vs. REB A.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-22', materialCode: 'MAT-0022', name: 'Monk Fruit 50%', supplier: 'Streamline', category: 'Sweetener', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Used in Relax & Unwind and Stress Relief sweetener systems.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-23', materialCode: 'MAT-0023', name: 'Vegetable Glycerin', supplier: 'Streamline', category: 'Base / Humectant', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'USP grade. Provides viscosity and mouthfeel. Used across kratom shot formulas.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-24', materialCode: 'MAT-0024', name: 'Citric Acid', supplier: 'Streamline', category: 'Acidulant', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Food grade anhydrous. Primary acidulant for pH control.', lastUpdated: '2025-01-10T09:00:00Z' },
    { id: 'mat-25', materialCode: 'MAT-0025', name: 'Vitamin B12 (Methylcobalamin)', supplier: 'Streamline', category: 'Vitamin', coaStatus: 'approved', rdApproved: true, commercialReady: true, notes: 'Methylcobalamin form. Used in Natural Energy and Trojan Horse at label-claim levels.', lastUpdated: '2025-01-10T09:00:00Z' },
  ],
}
