/**
 * One-shot seed script: loads SAMPLE_DATA into Supabase using the service_role key.
 *
 * Usage (run locally, never committed):
 *   1. Add to .env.local (NOT committed):
 *        SUPABASE_SERVICE_ROLE_KEY=eyJ...  (from Supabase → Project Settings → API)
 *   2. Apply migrations first (supabase/migrations/*.sql) via MCP or SQL editor.
 *   3. Run: npx tsx scripts/seed.ts
 *
 * This script bypasses RLS via the service_role key, which is why it must only
 * run locally and never land in client bundles.
 */

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'node:fs'
import { SAMPLE_DATA } from '../src/store/seedData'
import {
  projectToRow,
  formulationToRow,
  sampleToRow,
  feedbackToRow,
  gateReviewToRow,
  materialToRow,
  recipientToRow,
} from '../src/lib/api/mappers'

// Load .env.local manually so this works without a runner
const env = Object.fromEntries(
  readFileSync('.env.local', 'utf8')
    .split('\n')
    .filter((l) => l.trim() && !l.startsWith('#'))
    .map((l) => {
      const i = l.indexOf('=')
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()]
    })
)

const url = env.VITE_SUPABASE_URL
const serviceKey = env.SUPABASE_SERVICE_ROLE_KEY
if (!url || !serviceKey) {
  console.error(
    'Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local'
  )
  process.exit(1)
}

const supabase = createClient(url, serviceKey, {
  auth: { persistSession: false, autoRefreshToken: false },
})

// Map legacy string IDs (proj-1, form-1a, etc.) → new uuids generated by Postgres
const idMap = new Map<string, string>()

async function insertAndCapture<T extends { id: string }>(
  table: string,
  legacyId: string,
  row: Record<string, unknown>
) {
  const { data, error } = await supabase.from(table).insert(row).select('id').single()
  if (error) throw new Error(`${table} insert failed for ${legacyId}: ${error.message}`)
  idMap.set(legacyId, (data as T).id)
  return data
}

async function main() {
  console.log('Seeding Supabase…')

  // Materials: no FKs, safe to insert directly
  console.log(`  materials: ${SAMPLE_DATA.materials.length}`)
  for (const m of SAMPLE_DATA.materials) {
    const row = materialToRow(m)
    const { error } = await supabase.from('materials').insert(row)
    if (error) throw new Error(`materials insert failed for ${m.materialCode}: ${error.message}`)
  }

  // Projects
  console.log(`  projects: ${SAMPLE_DATA.projects.length}`)
  for (const p of SAMPLE_DATA.projects) {
    await insertAndCapture('projects', p.id, projectToRow(p))
  }

  // Formulations (remap project_id + parent_id)
  console.log(`  formulations: ${SAMPLE_DATA.formulations.length}`)
  for (const f of SAMPLE_DATA.formulations) {
    const row = {
      ...formulationToRow(f),
      project_id: idMap.get(f.projectId),
      parent_id: f.parentId ? idMap.get(f.parentId) ?? null : null,
    }
    await insertAndCapture('formulations', f.id, row)
  }

  // Samples (remap formulation_id + project_id)
  console.log(`  samples: ${SAMPLE_DATA.samples.length}`)
  for (const s of SAMPLE_DATA.samples) {
    const { recipients, ...rest } = s
    const row = {
      ...sampleToRow(rest),
      formulation_id: idMap.get(s.formulationId),
      project_id: idMap.get(s.projectId),
    }
    const { data, error } = await supabase.from('samples').insert(row).select('id').single()
    if (error) throw new Error(`samples insert failed for ${s.batchCode}: ${error.message}`)
    const newSampleId = (data as { id: string }).id
    idMap.set(s.id, newSampleId)
    if (recipients?.length) {
      const { error: rErr } = await supabase
        .from('sample_recipients')
        .insert(recipients.map((r) => recipientToRow(newSampleId, r)))
      if (rErr) throw new Error(`recipients insert failed for ${s.batchCode}: ${rErr.message}`)
    }
  }

  // Feedback (remap sample_id, formulation_id, project_id)
  console.log(`  feedback: ${SAMPLE_DATA.feedback.length}`)
  for (const fb of SAMPLE_DATA.feedback) {
    const row = {
      ...feedbackToRow(fb),
      sample_id: idMap.get(fb.sampleId),
      formulation_id: idMap.get(fb.formulationId),
      project_id: idMap.get(fb.projectId),
    }
    const { error } = await supabase.from('feedback').insert(row)
    if (error) throw new Error(`feedback insert failed: ${error.message}`)
  }

  // Gate reviews (remap project_id)
  console.log(`  gate_reviews: ${SAMPLE_DATA.gateReviews.length}`)
  for (const g of SAMPLE_DATA.gateReviews) {
    const row = {
      ...gateReviewToRow(g),
      project_id: idMap.get(g.projectId),
    }
    const { error } = await supabase.from('gate_reviews').insert(row)
    if (error) throw new Error(`gate_reviews insert failed: ${error.message}`)
  }

  console.log('✓ Seed complete.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
